## np.delete(): Remove items/rows/columns from Numpy Array

In [7]:
import numpy as np

## Delete an element in 1D Numpy Array by Index position

In [8]:
# Create a Numpy array from list of numbers
arr = np.array([4,5,6,7,8,9,10,11])
arr

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
                                                                # Delete element at index position 2
arr = np.delete(arr, 2)  #Delete the element 6 from the position 2
arr

array([ 4,  5,  7,  8,  9, 10, 11])

## Delete multiple elements in 1D Numpy Array by Index position

In [10]:
# Create a Numpy array from list of numbers
arr = np.array([4, 5, 6, 7, 8, 9, 10, 11])
                                                        # Delete element at index positions 1,2 and 3
arr = np.delete(arr, [1,2,3])
arr

array([ 4,  8,  9, 10, 11])

## Delete rows & columns from a 2D Numpy Array

In [11]:
# Create a 2D numpy array from list of list
arr2D = np.array([[11 ,12, 13, 11],
                  [21, 22, 23, 24],
                  [31, 32, 33, 34]])
arr2D

array([[11, 12, 13, 11],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

## Delete a column in 2D Numpy Array by column number

In [12]:
                                                                        # Delete column at index 1
arr2D = np.delete(arr2D, 1, axis=1)
arr2D

array([[11, 13, 11],
       [21, 23, 24],
       [31, 33, 34]])

## Delete multiple columns in 2D Numpy Array by column number

In [13]:
# Create a 2D numpy array from list of list
arr2D = np.array([[11 ,12, 13, 11],
                  [21, 22, 23, 24],
                  [31, 32, 33, 34]])
                                                                    # Delete column at index 2 and 3
arr2D = np.delete(arr2D, [2,3], axis=1)
arr2D

array([[11, 12],
       [21, 22],
       [31, 32]])

## Delete a row in 2D Numpy Array by row number

In [14]:
# Create a 2D numpy array from list of list
arr2D = np.array([[11 ,12, 13, 11],
                  [21, 22, 23, 24],
                  [31, 32, 33, 34]])
                                                        # Delete row at index 1 i.e. second row
arr2D = np.delete(arr2D, 1, axis=0)
arr2D

array([[11, 12, 13, 11],
       [31, 32, 33, 34]])

## Delete multiple rows in 2D Numpy Array by row number

In [15]:
# Create a 2D numpy array from list of list
arr2D = np.array([[11 ,12, 13, 11],
                  [21, 22, 23, 24],
                  [31, 32, 33, 34]])
arr2D

array([[11, 12, 13, 11],
       [21, 22, 23, 24],
       [31, 32, 33, 34]])

In [16]:
                                                                # Delete rows at ro1 1 and 2
arr2D = np.delete(arr2D, [1, 2], axis=0)
arr2D

array([[11, 12, 13, 11]])

# Delete specific elements in 1D Numpy Array by index position

In [20]:
# Create a Numpy array from list of numbers
arr = np.array([4,5,6,7,8,9,10,11])
arr

array([ 4,  5,  6,  7,  8,  9, 10, 11])

In [21]:
                                   # Delete element in row 1 and column 1 from 2D numpy array
modArr = np.delete(arr, 1) # Delete (5)
modArr

array([ 4,  6,  7,  8,  9, 10, 11])