In [13]:
import numpy as np 
a = np.array([[1,2],[3,4],[5,6]]) 
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
print ('Axis parameter not passed. The input array is flattened before insertion.')
a=np.insert(a,3,[11,12]) 
a

Axis parameter not passed. The input array is flattened before insertion.


array([ 1,  2,  3, 11, 12,  4,  5,  6])

In [15]:
a = np.array([[1,2],[3,4],[5,6]]) 
a


array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
                                                                # Insert [11, 12] at row 1
a=np.insert(a,1,[11, 12],axis = 0)
a

array([[ 1,  2],
       [11, 12],
       [ 3,  4],
       [ 5,  6]])

In [17]:
                                                                    # Insert [7,8, 9, 10] at column 1
a=np.insert(a,1,[7,8, 9, 10],axis = 1)
a

array([[ 1,  7,  2],
       [11,  8, 12],
       [ 3,  9,  4],
       [ 5, 10,  6]])